language: objective-c
osx_image: xcode10
branches:
  only:
    - master
script:
  - xcodebuild -scheme KAAOptional -workspace KAAOptional.xcworkspace -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7"  -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash)
